// Scans public/terraria/bg/{far,mid,near}/{day,night,both}/ and generates bgManifest.ts
// Run: bun run gen:bg
import { readdirSync, existsSync, writeFileSync } from 'fs'
import { join } from 'path'

const PUBLIC_BG = join(import.meta.dir, '../public/terraria/bg')
const OUTPUT = join(import.meta.dir, '../src/screens/TerrariaMenu/bgManifest.ts')

const depths = ['far', 'mid', 'near'] as const
const times = ['day', 'night', 'both'] as const

function getFiles(folder: string): string[] {
  const dir = join(PUBLIC_BG, folder)
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter(f => f.endsWith('.webp') || f.endsWith('.png'))
    .sort()
    .map(f => `/terraria/bg/${folder}/${f}`)
}

const pool: Record<string, Record<string, string[]>> = {}
for (const depth of depths) {
  pool[depth] = {}
  for (const time of times) {
    pool[depth]![time] = getFiles(`${depth}/${time}`)
  }
}

const totalFiles = Object.values(pool).flatMap(d => Object.values(d)).flat().length

const content = `// DO NOT EDIT — auto-generated by scripts/gen-bg-manifest.ts
// Move images between far/mid/near and day/night/both folders, then run: bun run gen:bg

export const BG_POOL: Record<string, Record<string, string[]>> = ${JSON.stringify(pool, null, 2)}
`

writeFileSync(OUTPUT, content)
console.log(`✓ bgManifest.ts generated (${totalFiles} files across ${depths.length * times.length} folders)`)
for (const depth of depths) {
  for (const time of times) {
    const count = pool[depth]![time]!.length
    if (count > 0) console.log(`  ${depth}/${time}: ${count} files`)
  }
}
